image: ubuntu:16.04

pipelines:
  branches:
    release:
      - step:
          caches:
            - node
          script:
            - export LANG=C.UTF-8
            - apt-get -q update
            - apt-get -q -y install npm nodejs curl wget
            - ln -s /usr/bin/nodejs /usr/bin/node
            - npm cache clean -f
            - npm install -g n
            - n stable
            - npm config set registry http://registry.npmjs.org/
            - npm install -g cordova ionic
            - npm install --unsafe-perm
            - ionic build android --prod --release
            - curl -X PUT -d 'data={"keys":{"android":{"id":"'$PHONEGAP_ANDROID_CERT_ID'","key_pw":"'$PHONEGAP_ANDROID_KEY_PASSWORD'","keystore_pw":"'$PHONEGAP_ANDROID_KEYSTORE_PASSWORD'"},"ios":{"id":"'$PHONEGAP_IOS_CERT_ID'","password":"'$PHONEGAP_IOS_CERT_PASSWORD'"}}}' https://build.phonegap.com/api/v1/apps/${PHONEGAP_APP_ID}?auth_token=${PHONEGAP_AUTH_TOKEN}
            - ./node_modules/grunt-cli/bin/grunt deploy --appid="${PHONEGAP_APP_ID}" --authtoken="${PHONEGAP_AUTH_TOKEN}"